# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
  {id: 0 ,size: 0.172, name: "0"},
  {id: 1 ,size: 0.172, name: "1"},
  {id: 2 ,size: 0.172, name: "2"},
  {id: 3 ,size: 0.172, name: "3"},
  {id: 4 ,size: 0.172, name: "4"},
  {id: 5 ,size: 0.172, name: "5"},
  {id: 6 ,size: 0.172, name: "6"},
  {id: 7 ,size: 0.172, name: "7"},
  {id: 8 ,size: 0.172, name: "8"},
  {id: 9 ,size: 0.172, name: "9"},
  {id: 10 ,size: 0.172, name: "10"},
  {id: 11 ,size: 0.172, name: "11"},
  {id: 12 ,size: 0.172, name: "12"},
  {id: 13 ,size: 0.172, name: "13"},
  {id: 14 ,size: 0.172, name: "14"},
  {id: 15 ,size: 0.172, name: "15"},
  {id: 16 ,size: 0.172, name: "16"},
  {id: 17 ,size: 0.172, name: "17"},
  {id: 18 ,size: 0.172, name: "18"},
  {id: 19 ,size: 0.172, name: "19"},
  {id: 20 ,size: 0.172, name: "20"},
  {id: 21 ,size: 0.172, name: "21"},
  {id: 22 ,size: 0.172, name: "22"},
  {id: 23 ,size: 0.172, name: "23"},
  {id: 24 ,size: 0.172, name: "24"},
  {id: 25 ,size: 0.172, name: "25"},
  {id: 26 ,size: 0.172, name: "26"},
  {id: 27 ,size: 0.172, name: "27"},
  {id: 28 ,size: 0.172, name: "28"},
  {id: 29 ,size: 0.172, name: "29"},
  {id: 30 ,size: 0.172, name: "30"},
  {id: 31 ,size: 0.172, name: "31"},
  {id: 32 ,size: 0.172, name: "32"},
  {id: 33 ,size: 0.172, name: "33"},
  {id: 34 ,size: 0.172, name: "34"},
  {id: 35 ,size: 0.172, name: "35"},
  {id: 36 ,size: 0.172, name: "36"},
  {id: 37 ,size: 0.172, name: "37"},
  {id: 38 ,size: 0.172, name: "38"},
  {id: 39 ,size: 0.172, name: "39"},
  {id: 40 ,size: 0.172, name: "40"},
  {id: 41 ,size: 0.172, name: "41"},
  {id: 42 ,size: 0.172, name: "42"},
  {id: 43 ,size: 0.172, name: "43"},
  {id: 44 ,size: 0.172, name: "44"},
  {id: 45 ,size: 0.172, name: "45"},
  {id: 46 ,size: 0.172, name: "46"},
  {id: 47 ,size: 0.172, name: "47"},
  {id: 48 ,size: 0.172, name: "48"},
  {id: 49 ,size: 0.172, name: "49"},
  {id: 50 ,size: 0.172, name: "40"},
  {id: 51 ,size: 0.172, name: "51"},
  {id: 52 ,size: 0.172, name: "52"},
  {id: 53 ,size: 0.172, name: "53"},
  {id: 54 ,size: 0.037, name: "54"},
  {id: 55 ,size: 0.034, name: "55"},
  {id: 56 ,size: 0.031, name: "56"},
  {id: 57 ,size: 0.051, name: "57"},
  {id: 58 ,size: 0.172, name: "58"},
  {id: 59 ,size: 0.172, name: "59"},
  {id: 60 ,size: 0.172, name: "50"},
  {id: 61 ,size: 0.037, name: "61"},
  {id: 62 ,size: 0.034, name: "62"},
  {id: 63 ,size: 0.031, name: "63"},
  {id: 64 ,size: 0.051, name: "64"},
  {id: 65 ,size: 0.172, name: "65"},
  {id: 66 ,size: 0.172, name: "66"},
  {id: 67 ,size: 0.172, name: "67"},
  {id: 68 ,size: 0.037, name: "68"},
  {id: 69 ,size: 0.034, name: "69"},
  {id: 70 ,size: 0.031, name: "70"},
  {id: 71 ,size: 0.051, name: "71"},
  {id: 72 ,size: 0.172, name: "72"},
  {id: 73 ,size: 0.172, name: "73"},
  {id: 74 ,size: 0.172, name: "74"},
  {id: 75 ,size: 0.037, name: "75"},
  {id: 76 ,size: 0.034, name: "76"},
  {id: 77 ,size: 0.031, name: "77"},
  {id: 78 ,size: 0.031, name: "78"},
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
  ]
